server:
  address: ":8080"

mongo:
  uri: "mongodb://mongoroot:secret@localhost:27017/?authSource=admin"
  database: "taskdb"

kafka:
  enabled: true
  brokers: ["UPSTASH_ENDPOINT"]
  topic: "task-events"
  partitions: 3
  replication: 1
  security:
    protocol: "SASL_SSL"
    username: "UPSTASH_USERNAME"
    password: "UPSTASH_PASSWORD"
