server:
  address: ":8080"

mongo:
  uri: "mongodb://mongoroot:secret@localhost:27017/?authSource=admin"
  database: "taskdb"

rabbitmq:
  enabled: true
  url: "amqp://guest:guest@localhost:5672/"
  exchange: "task-events"
  queue: "task-events-queue"