version: '3.8'

services:
  mongo:
    container_name: mongo
    image: mongo:6.0.3
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=mongoroot"
      - "MONGO_INITDB_ROOT_PASSWORD=secret"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: