version: '3.8'

services:
  # MongoDB
  mongo:
    container_name: mongo
    image: mongo:6.0.3
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=mongoroot"
      - "MONGO_INITDB_ROOT_PASSWORD=secret"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  # RabbitMQ
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management  # Incluye Management UI
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 30s
      retries: 3

  # Backend Go service
  taskservice:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: taskservice
    ports:
      - "8080:8080"
    depends_on:
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      - TASK_SERVER_ADDRESS=:8080
      - TASK_MONGO_URI=mongodb://mongoroot:secret@mongo:27017/taskdb?authSource=admin
      - TASK_RABBITMQ_ENABLED=true
      - TASK_RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - TASK_RABBITMQ_EXCHANGE=task-events
      - TASK_RABBITMQ_QUEUE=task-events-queue
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Vue.js + Nginx
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      taskservice:
        condition: service_healthy
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  mongo-data:
  rabbitmq-data:

networks:
  app-network:
    driver: bridge
